################################
# BASE
################################
enable
configure terminal
hostname Switch-A
no ip routing
no ip domain-lookup

################################
# VLANs
################################
vlan 10
 name NetAdmin
vlan 20
 name SysAdmin
vlan 30
 name NetDev
exit

################################
# DHCP SNOOPING
################################
ip dhcp snooping
ip dhcp snooping vlan 10,20,30
no ip dhcp snooping information option

################################
# DYNAMIC ARP INSPECTION
################################
ip arp inspection vlan 10,20,30

################################
# INTERFACE TRUNK VERS FORTIGATE
################################
interface Gi0/0
 description TRUNK_TO_FORTIGATE-A
 switchport trunk encapsulation dot1q
 switchport mode trunk
 switchport trunk allowed vlan 10,20,30
 ip dhcp snooping trust
 ip arp inspection trust
exit

################################
# PORTS UTILISATEURS
################################
interface Gi0/1
 description USER_VLAN10
 switchport mode access
 switchport access vlan 10
 spanning-tree portfast
 switchport port-security
 switchport port-security maximum 2
 switchport port-security violation shutdown
 switchport port-security mac-address sticky
exit

interface Gi0/2
 description USER_VLAN20
 switchport mode access
 switchport access vlan 20
 spanning-tree portfast
 switchport port-security
 switchport port-security maximum 2
 switchport port-security violation shutdown
 switchport port-security mac-address sticky
exit

interface Gi0/3
 description SERVER_VLAN30
 switchport mode access
 switchport access vlan 30
 spanning-tree portfast
 switchport port-security
 switchport port-security maximum 1
 switchport port-security violation shutdown
 switchport port-security mac-address sticky
exit

do write
end
